### ISSUE TITLE
Included list support for Encoding

### ISSUE THREAD

**Issue by kvaljeva** [infinum/Japx#10]
## Expected Behavior
Updating relationships should be done by including objects into a list which should be encoded into the top level object. Basically, we'd need support for all top level objects besides data.
```
{
     "data": "...",
     "meta":"...",
     "included":"..."
}
```
## Actual Behavior
What happens now is that all of the objects that are set in an included list end up being flattened into `data.attributes`
```
{
     "data": {
          "attributes": {
               "included":"..."
          }
     }
}
```

## Steps to Reproduce the Problem

  1. Create a top level Request object that has other top level properties other than data
  2. Encode the object with JAPX

**Comment by Leta0n** [comment]
@kvaljeva Why this issue is closed?
Any plans to support `included` in Encoder?

**Comment by Truba** [comment]
Hi @Leta0n , @havebeenfitz 
Unfortunately `included` in creating/updating is not officially supported by the JSON:API [standard](https://jsonapi.org/format/#crud)
I've written a few more word about that topic in issue #29 .

But until something like [operations](https://github.com/json-api/json-api/pull/1254) is accepted into the standard this remains one of the main JSON:API pain points.
