### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by sebastian-grabinski** [infinum/Japx#13]
Hi guys, is there any way that in the future there will be support for carthage? 

Thanks!

**Comment by magnifique0** [comment]
Hi @Truba! :) 

Yeah, I tried to do it, at the first sight it should be easy, but unfortunately at the end `Carthage` showed me that Framework is not `shared` so dunno what was wrong.. 

I've used this tut 
https://medium.com/@filippotosetto/how-to-create-a-carthage-framework-8d9d65f98ac2

Maybe you will figure it out :)

**Comment by joaopedro1520** [comment]
This would be really nice!

**Comment by peredaniel** [comment]
Hi guys!

I know this is an old issue, but it seems that there has been no progress on it. I need Japx as a dependency on a framework, and we already use Carthage to manage dependencies. Do you mind if I add Carthage support and open a PR when done?

Thanks! :)

**Comment by abin0992** [comment]
Still no Carthage support? :(

**Comment by Truba** [comment]
Hi guys,
I’m sorry for being absent for this long.
@peredaniel This is great news :) I would really really appreciate it if you can make a pull request?
If you are not familiar with creating pull requesting from a fork, you can find instruction on how to do it [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by abin0992** [comment]
@Truba  I have opened a [PR for adding Carthage support](https://github.com/infinum/Japx/pull/32) Please review it :)

**Comment by peredaniel** [comment]
@Truba Sorry for not coming back to you sooner. I believe I do have the changes in my local, so I can upload them at any time. The changes were extensive, since I had to add an Xcode project and move a lot of files.

**Comment by abin0992** [comment]
@peredaniel  Thanks for updating. I will close my PR, the changes I made are not working with Carthage.

**Comment by Dundo7** [comment]
Hello, we have added Carthage support for Japx. It will be in the next release which we will do this week.
