### ISSUE TITLE
How pars meta

### ISSUE THREAD

**Issue by Draiseen** [infinum/Japx#14]
Hello, I try parse this response 
```javascript
{
  "data": [
    {
      "type": "messages",
      "id": "1",
      "attributes": {
        "text": "qqq",
        "create_date": "2017-06-09T09:35:34.428523"
      },
      "meta": {
        "unread": true
      }
    }
  ]
}
```

this model not work

```swift
struct JapxResponse<T: Codable>: Codable {
  let data: T
}

struct MessageModel: JapxCodable, Equatable, Hashable {
  let type: String
  let id: String
  let text: String
  let createDate: String
  let unread: Bool

  enum CodingKeys: String, CodingKey {
    case type, id, text, createDate = "create_date", unread
  }
}
```

help pls, ty

**Comment by Truba** [comment]
Please find JapxApp in attachment.
It's a mac app that does decoding and encoding of JSON:API. It's something that we created using Japx to reduce thinking process when creating models in our code :)
[JapxApp.zip](https://github.com/infinum/Japx/files/2411449/JapxApp.zip)

**Comment by Draiseen** [comment]
Thanks for answer.
Cool application.
Why you don't merge the meta object into the root object?

**Comment by Draiseen** [comment]
I have error((
debugDescription : "No value associated with key CodingKeys(stringValue: \"meta\", intValue: nil) (\"meta\")."

**Comment by Truba** [comment]
> Why you don't merge the meta object into the root object?
You can have properties with the same names in meta, attributes, and we don't want to override any of those properties.
i.e. You could have `unread` property in meta and in attributes.

**Comment by Truba** [comment]
> I have error((
> debugDescription : "No value associated with key CodingKeys(stringValue: \"meta\", intValue: nil) (\"meta\")."

This is `JSONDecoder` error if you don't have value in your json. Are you sure you have your meta object in your message object from the json you are trying to decode?

**Comment by Draiseen** [comment]
After call this method data not contained `meta` object
```swift
let data = try Japx.Decoder.data(with: data, includeList: includeList)
```

**Comment by Draiseen** [comment]
Oh, im so sorry, i forgot delete `meta` from included lists, apparently because of this and disappeared object " meta"

**Comment by fgulan** [comment]
@Draiseen so you have managed to solve your issue? 🙂

**Comment by Draiseen** [comment]
yep)
