### ISSUE TITLE
Moya/RxSwift update to 12.0.1

### ISSUE THREAD

**Issue by JohnKuan** [infinum/Japx#15]
## Expected Behavior
Moya/RxSwift has updated to version 12.0.1

## Actual Behavior
Currently Moya flavoured pods are pointing to version 11.0

## Specifications

  - Version: 1.0.3
  - Platform: iOS

Is it possible to consider updating to v12.0.1 for Moya dependencies at this point?

**Comment by fgulan** [comment]
We've bumped Japx (v2.0.0) to use Moya 12.0 https://github.com/infinum/Japx/pull/17
