### ISSUE TITLE
Example CRUD using Codable and Alamofire

### ISSUE THREAD

**Issue by gfvilela** [infinum/Japx#29]
I need an example code of a CRUD using Codable and Alamofire. Because the support documentation has simples examples and I would like to know the best practices for this implementation.

**Comment by MateMasnov** [comment]
Hey @gfvilela, we made an [example](https://github.com/infinum/iOS-Nuts-And-Bolts/tree/master/Catalog/Examples/Networking/Japx) of CRUD operations with Japx on our [repository](https://github.com/infinum/iOS-Nuts-And-Bolts) 
with commonly used code.

Feel free to clone and check the rest of our repo :)

**Comment by Truba** [comment]
This should be resolved.
Closing for now.
