### ISSUE TITLE
Not compatible with XCFramework

### ISSUE THREAD

**Issue by sbelmeha** [infinum/Japx#40]
## Expected Behavior
Could be used for XCFramework

## Actual Behavior
Can not be used for XCFramework, the reason is that a class/struct in the framework has the same name as the framework - "Japx".
Discussion on swift forum - https://forums.swift.org/t/frameworkname-is-not-a-member-type-of-frameworkname-errors-inside-swiftinterface/28962
This is a known issue and needs a workaround

## Steps to Reproduce the Problem

  1. Build XCFramework with Japx as a cocoa pod dependencie
  2. Try to use XCFramework as a cocoa pod dependencie
  3. As a result an error occurs:
`'JapxDecodable' is not a member type of 'Japx'`

## Specifications

  - Version: Xcode 12.0.1, Japx 3.0.0

## Proposed Workaround
Rename `Japx` struct.

**Comment by Dundo7** [comment]
Hello, we renamed `Japx` struct to `JapxKit`. It is merged into master and we will do a release this week.
