### ISSUE TITLE
SPM - import Japx without the rest of the dependencies 

### ISSUE THREAD

**Issue by johnldeguzman** [infinum/Japx#54]
## Expected Behavior
Easily import japx and japxCore without having to import Moya, Alamofire, etc. 

## Actual Behavior
SPM downloads the whole package and it's dependencies causing dependency resolution issues despite not wanting to use the other targets. 

i.e. Want to use japx and japxcore but not japxrxalamofire but still imports all dependencies causing existing alamofire to have dependency resolution issues

## Steps to Reproduce the Problem

  1.
```
.package(
    url: "https://github.com/infinum/Japx",
    .exact("4.0.0")
)
```

## Specifications

  - Version: 4.0.1
  - Platform: iOS
  - Subsystem:

**Comment by EmDee** [comment]
For anyone that stumbles over this. As of today (May 12th 2022), this is a shortcoming of SPM: https://stackoverflow.com/questions/68408989/swift-package-manager-target-based-dependency
