### ISSUE TITLE
Add privacy manifest per app store guidelines starting May 2024

### ISSUE THREAD

**Issue by RushanB** [infinum/Japx#59]
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by hhrvoic** [comment]
@RushanB did you experience some issues with uploading your app to the Appstore? I did a quick check and seems like we are not using any APIs that imply definition of privacy manifest. If not, feel free to close the issue. 

Similar topic on RxSwift community: 

https://github.com/ReactiveX/RxSwift/issues/2567#issuecomment-2076898104
https://github.com/ReactiveX/RxSwift/issues/2607#issuecomment-2147301557

**Comment by Stephen-Doughty** [comment]
This was returned today:

ITMS-91061: Missing privacy manifest
- Your app includes “Frameworks/RxSwift.framework/RxSwift”, which includes OneSignalOutcomes, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. Starting November 12, 2024, if a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit:
https://developer.apple.com/support/third-party-SDK-requirements
.
